export default {
    //乘客类型
    passengerType:{
        1:'成人票',
        2:'儿童票'
    },
    passengerTypeRange:[
        '成人票',
        '儿童票'
    ],
    passengerTypeList:[
        {
            value:1,
            label:'成人票'
        },
        {
            value:2,
            label:'儿童票'

        }
    ],
    //证件类型
    certificateType:{
        2:'护照',
        3:'港澳通行证',
        5:'回乡证',
        7:'台胞证'
    },
    certificateTypeRange:[
        '护照',
        '港澳通行证',
        '回乡证',
        '台胞证'
    ],
    certificateTypeList:[
        {
            value:2,
            label:'护照'
        },
        {
            value:3,
            label:'港澳通行证'
        },
        {
            value:5,
            label:'回乡证'
        },
        {
            value:7,
            label:'台胞证'
        }
    ],
}